version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      avalonia:
        patterns:
          - "Avalonia*"
      test-tooling:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
